package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class New_Feature_DisjointUnion_001 {
	@Test
	public void testNew_Feature_DisjointUnion_001() {
		String premise = "<?xml version=\"1.0\"?>\n" + "<rdf:RDF\n"
				+ "  xml:base  = \"http://example.org/\"\n"
				+ "  xmlns     = \"http://example.org/\"\n"
				+ "  xmlns:owl = \"http://www.w3.org/2002/07/owl#\"\n"
				+ "  xmlns:rdf = \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
				+ "\n" + "<owl:Ontology/>\n" + "\n"
				+ "<owl:Class rdf:about=\"Child\" />\n"
				+ "<owl:Class rdf:about=\"Boy\" />\n"
				+ "<owl:Class rdf:about=\"Girl\" />\n" + "\n"
				+ "<rdf:Description rdf:about=\"Child\">\n"
				+ "  <owl:disjointUnionOf rdf:parseType=\"Collection\">\n"
				+ "    <rdf:Description rdf:about=\"Boy\" />\n"
				+ "    <rdf:Description rdf:about=\"Girl\" />\n"
				+ "  </owl:disjointUnionOf>\n" + "</rdf:Description>\n" + "\n"
				+ "<Child rdf:about=\"Stewie\" />\n"
				+ "<rdf:Description rdf:about=\"Stewie\">\n" + "  <rdf:type>\n"
				+ "    <owl:Class>\n"
				+ "      <owl:complementOf rdf:resource=\"Girl\" />\n"
				+ "    </owl:Class>\n" + "  </rdf:type>\n" + "</rdf:Description>\n"
				+ "\n" + "</rdf:RDF>";
		String conclusion = "<?xml version=\"1.0\"?>\n" + "<rdf:RDF\n"
				+ "  xml:base  = \"http://example.org/\"\n"
				+ "  xmlns     = \"http://example.org/\"\n"
				+ "  xmlns:owl = \"http://www.w3.org/2002/07/owl#\"\n"
				+ "  xmlns:rdf = \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
				+ "\n" + "<owl:Ontology/>\n" + "\n" + "<owl:Class rdf:about=\"Boy\" />\n"
				+ "\n" + "<Boy rdf:about=\"Stewie\" />\n" + "\n" + "</rdf:RDF>";
		String id = "New_Feature_DisjointUnion_001";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "Demonstrates a disjoint union axiom based on the example in the Structural Specification and Functional-Style Syntax document.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
