package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class New_Feature_DisjointObjectProperties_002 {
    @Test
    public void testNew_Feature_DisjointObjectProperties_002() {
        String premise = "<?xml version=\"1.0\"?>\n" + "<rdf:RDF\n"
                + "  xml:base  = \"http://example.org/\"\n"
                + "  xmlns     = \"http://example.org/\"\n"
                + "  xmlns:owl = \"http://www.w3.org/2002/07/owl#\"\n"
                + "  xmlns:rdf = \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
                + "\n" + "<owl:Ontology/>\n" + "\n"
                + "<owl:ObjectProperty rdf:about=\"hasFather\" />\n"
                + "<owl:ObjectProperty rdf:about=\"hasMother\" />\n"
                + "<owl:ObjectProperty rdf:about=\"hasChild\" />\n" + "\n"
                + "<owl:AllDisjointProperties>\n"
                + "  <owl:members rdf:parseType=\"Collection\">\n"
                + "    <rdf:Description rdf:about=\"hasFather\" />\n"
                + "    <rdf:Description rdf:about=\"hasMother\" />\n"
                + "    <rdf:Description rdf:about=\"hasChild\" />\n"
                + "  </owl:members>\n" + "</owl:AllDisjointProperties>\n" + "\n"
                + "<rdf:Description rdf:about=\"Stewie\">\n"
                + "  <hasFather rdf:resource=\"Peter\" />\n" + "</rdf:Description>\n"
                + "\n" + "<rdf:Description rdf:about=\"Stewie\">\n"
                + "  <hasMother rdf:resource=\"Lois\" />\n" + "</rdf:Description>\n"
                + "\n" + "<rdf:Description rdf:about=\"Stewie\">\n"
                + "  <hasChild rdf:resource=\"StewieJr\" />\n" + "</rdf:Description>\n"
                + "\n" + "</rdf:RDF>";
        String conclusion = "<?xml version=\"1.0\"?>\n" + "<rdf:RDF\n"
                + "  xml:base  = \"http://example.org/\"\n"
                + "  xmlns     = \"http://example.org/\"\n"
                + "  xmlns:owl = \"http://www.w3.org/2002/07/owl#\"\n"
                + "  xmlns:rdf = \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">\n"
                + "\n" + "<owl:Ontology/>\n" + "\n" + "<owl:AllDifferent>\n"
                + "  <owl:distinctMembers rdf:parseType=\"Collection\">\n"
                + "    <rdf:Description rdf:about=\"Peter\" />\n"
                + "    <rdf:Description rdf:about=\"Lois\" />\n"
                + "    <rdf:Description rdf:about=\"StewieJr\" />\n"
                + "  </owl:distinctMembers>\n" + "</owl:AllDifferent>\n" + "\n"
                + "</rdf:RDF>";
        String id = "New_Feature_DisjointObjectProperties_002";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "A modification of test New-Feature-DisjointObjectProperties-001 to demonstrate a ternary disjoint object properties axiom.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
