package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class owl2_rl_valid_mincard {
	@Test
	public void testowl2_rl_valid_mincard() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
				+ "    xmlns:j.0=\"http://owl2.test/rules#\">\n"
				+ "  <owl:Ontology rdf:about=\"http://org.semanticweb.ontologies/Ontology1232054810511161000\"/>\n"
				+ "  <owl:Class rdf:about=\"http://owl2.test/rules#C\">\n"
				+ "    <rdfs:subClassOf>\n"
				+ "      <owl:Restriction>\n"
				+ "        <owl:minCardinality rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
				+ "        >1</owl:minCardinality>\n"
				+ "        <owl:onProperty>\n"
				+ "          <owl:ObjectProperty rdf:about=\"http://owl2.test/rules#OP\"/>\n"
				+ "        </owl:onProperty>\n"
				+ "      </owl:Restriction>\n"
				+ "    </rdfs:subClassOf>\n"
				+ "  </owl:Class>\n"
				+ "  <owl:Class rdf:about=\"http://www.w3.org/2002/07/owl#Thing\"/>\n"
				+ "  <j.0:C rdf:about=\"http://owl2.test/rules#c\">\n"
				+ "    <rdf:type rdf:resource=\"http://www.w3.org/2002/07/owl#Thing\"/>\n"
				+ "  </j.0:C>\n" + "</rdf:RDF>";
		String conclusion = "";
		String id = "owl2_rl_valid_mincard";
		TestClasses tc = TestClasses.valueOf("CONSISTENCY");
		String d = "OWL 2 RL does not allow min cardinality";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
