package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class owl2_rl_invalid_leftside_maxcard {
	@Test
	public void testowl2_rl_invalid_leftside_maxcard() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\">\n"
				+ "  <owl:Ontology />\n"
				+ "  <owl:Class rdf:about=\"http://owl2.test/rules#C\"/>\n"
				+ "  <owl:ObjectProperty rdf:about=\"http://owl2.test/rules#op\"/>\n"
				+ "  <owl:Restriction>\n"
				+ "    <rdfs:subClassOf rdf:resource=\"http://owl2.test/rules#C\"/>\n"
				+ "    <owl:maxCardinality rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
				+ "    >2</owl:maxCardinality>\n"
				+ "    <owl:onProperty rdf:resource=\"http://owl2.test/rules#op\"/>\n"
				+ "  </owl:Restriction>\n" + "</rdf:RDF>";
		String conclusion = "";
		String id = "owl2_rl_invalid_leftside_maxcard";
		TestClasses tc = TestClasses.valueOf("CONSISTENCY");
		String d = "Invalid OWL 2 RL due to maxCardinality usage.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
