package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class owl2_rl_rules_fp_differentFrom {
	@Test
	public void testowl2_rl_rules_fp_differentFrom() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:j.0=\"http://owl2.test/rules/\">\n"
				+ "  <owl:Ontology />\n"
				+ "  <owl:FunctionalProperty rdf:about=\"http://owl2.test/rules/fp\">\n"
				+ "    <rdf:type rdf:resource=\"http://www.w3.org/2002/07/owl#ObjectProperty\"/>\n"
				+ "  </owl:FunctionalProperty>\n"
				+ "  <owl:NamedIndividual rdf:about=\"http://owl2.test/rules/Y2\">\n"
				+ "    <j.0:fp>\n"
				+ "      <owl:NamedIndividual rdf:about=\"http://owl2.test/rules/X2\"/>\n"
				+ "    </j.0:fp>\n" + "  </owl:NamedIndividual>\n"
				+ "  <owl:NamedIndividual rdf:about=\"http://owl2.test/rules/X1\">\n"
				+ "    <owl:differentFrom rdf:resource=\"http://owl2.test/rules/X2\"/>\n"
				+ "  </owl:NamedIndividual>\n"
				+ "  <owl:NamedIndividual rdf:about=\"http://owl2.test/rules/Y1\">\n"
				+ "    <j.0:fp rdf:resource=\"http://owl2.test/rules/X1\"/>\n"
				+ "  </owl:NamedIndividual>\n" + "</rdf:RDF>";
		String conclusion = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\">\n"
				+ "  <owl:Ontology />\n"
				+ "  <owl:NamedIndividual rdf:about=\"http://owl2.test/rules/Y2\"/>\n"
				+ "  <owl:NamedIndividual rdf:about=\"http://owl2.test/rules/Y1\">\n"
				+ "    <owl:differentFrom rdf:resource=\"http://owl2.test/rules/Y2\"/>\n"
				+ "  </owl:NamedIndividual>\n" + "</rdf:RDF>";
		String id = "owl2_rl_rules_fp_differentFrom";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "This test checks the interaction between an OWL functional property and differentFrom assertions.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
