package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class rdfbased_sem_ndis_alldifferent_fw {
	@Test
	public void testrdfbased_sem_ndis_alldifferent_fw() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
				+ "    xmlns:ex=\"http://www.example.org#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\">\n"
				+ "  <owl:AllDifferent rdf:about=\"http://www.example.org#z\">\n"
				+ "    <owl:members rdf:parseType=\"Collection\">\n"
				+ "      <rdf:Description rdf:about=\"http://www.example.org#w1\">\n"
				+ "        <owl:sameAs rdf:resource=\"http://www.example.org#w2\"/>\n"
				+ "      </rdf:Description>\n"
				+ "      <rdf:Description rdf:about=\"http://www.example.org#w2\"/>\n"
				+ "      <rdf:Description rdf:about=\"http://www.example.org#w3\"/>\n"
				+ "    </owl:members>\n" + "  </owl:AllDifferent>\n" + "</rdf:RDF>";
		String conclusion = "";
		String id = "rdfbased_sem_ndis_alldifferent_fw";
		TestClasses tc = TestClasses.valueOf("INCONSISTENCY");
		String d = "All the members of an owl:AllDifferent construct are mutually different individuals.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
