package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class rdfbased_sem_char_asymmetric_term {
	@Test
	public void testrdfbased_sem_char_asymmetric_term() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
				+ "    xmlns:ex=\"http://www.example.org#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\">\n"
				+ "  <owl:SymmetricProperty rdf:about=\"http://www.example.org#p\">\n"
				+ "    <rdf:type rdf:resource=\"http://www.w3.org/2002/07/owl#AsymmetricProperty\"/>\n"
				+ "  </owl:SymmetricProperty>\n"
				+ "  <rdf:Description rdf:about=\"http://www.example.org#x\">\n"
				+ "    <ex:p rdf:resource=\"http://www.example.org#y\"/>\n"
				+ "  </rdf:Description>\n" + "</rdf:RDF>";
		String conclusion = "";
		String id = "rdfbased_sem_char_asymmetric_term";
		TestClasses tc = TestClasses.valueOf("INCONSISTENCY");
		String d = "A non-empty property cannot be both symmetrical and asymmetrical.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
