package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class rdfbased_sem_class_nothing_ext {
	@Test
	public void testrdfbased_sem_class_nothing_ext() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
				+ "    xmlns:ex=\"http://www.example.org#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\">\n"
				+ "  <owl:Nothing rdf:about=\"http://www.example.org#x\"/>\n"
				+ "</rdf:RDF>";
		String conclusion = "";
		String id = "rdfbased_sem_class_nothing_ext";
		TestClasses tc = TestClasses.valueOf("INCONSISTENCY");
		String d = "The extension of the vocabulary class owl:Nothing is empty.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
