package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_equivalentClass_005 {
    @Test
    public void testWebOnt_equivalentClass_005() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/equivalentClass/premises005\" >\n"
                + "    <owl:Ontology/>\n"
                + "    <owl:Class rdf:ID=\"c1\">\n"
                + "      <rdfs:subClassOf>\n"
                + "                <owl:Restriction>\n"
                + "                   <owl:onProperty rdf:resource=\"#p\"/>\n"
                + "                   <owl:cardinality\n"
                + " rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
                + "                   >1</owl:cardinality>\n"
                + "                </owl:Restriction>\n"
                + "       </rdfs:subClassOf>\n"
                + "     </owl:Class>\n"
                + "    <owl:Class rdf:ID=\"c2\">\n"
                + "      <rdfs:subClassOf>\n"
                + "                <owl:Restriction>\n"
                + "                   <owl:onProperty rdf:resource=\"#p\"/>\n"
                + "                   <owl:cardinality\n"
                + " rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
                + "                   >1</owl:cardinality>\n"
                + "                </owl:Restriction>\n" + "       </rdfs:subClassOf>\n"
                + "     </owl:Class>\n" + "     <owl:ObjectProperty rdf:ID=\"p\"/>\n"
                + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/equivalentClass/nonconclusions005\" >\n"
                + "    <owl:Ontology/>\n" + "<owl:Class rdf:about=\"premises005#c1\">\n"
                + "     <owl:equivalentClass>\n"
                + "       <owl:Class rdf:about=\"premises005#c2\"/>\n"
                + "     </owl:equivalentClass>\n" + "  </owl:Class>\n" + "</rdf:RDF>";
        String id = "WebOnt_equivalentClass_005";
        TestClasses tc = TestClasses.valueOf("NEGATIVE_IMPL");
        String d = "Two classes with the same partial description are not equivalent.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
