package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_unionOf_004 {
	@Test
	public void testWebOnt_unionOf_004() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/unionOf/premises004#\"\n"
				+ "    xmlns:second=\"http://www.w3.org/2002/03owlt/unionOf/conclusions004#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/unionOf/premises004\" >\n"
				+ "\n" + "   <owl:Ontology/>\n" + "\n"
				+ "   <owl:Class rdf:about=\"#A-and-B\">\n"
				+ "     <owl:unionOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Class rdf:about=\"#A\"/>\n"
				+ "       <owl:Class rdf:about=\"#B\"/>\n" + "     </owl:unionOf>\n"
				+ "   </owl:Class>\n" + "\n" + "   <owl:Class rdf:ID=\"A\">\n"
				+ "     <owl:oneOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Thing rdf:ID=\"a\"/>\n" + "     </owl:oneOf>\n"
				+ "   </owl:Class>\n" + "   <owl:Class rdf:ID=\"B\">\n"
				+ "     <owl:oneOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Thing rdf:ID=\"b\"/>\n" + "     </owl:oneOf>\n"
				+ "   </owl:Class>\n" + "\n" + "</rdf:RDF>";
		String conclusion = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/unionOf/premises004#\"\n"
				+ "    xmlns:second=\"http://www.w3.org/2002/03owlt/unionOf/conclusions004#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/unionOf/conclusions004\" >\n"
				+ "\n" + "   <owl:Ontology/>\n" + "\n"
				+ "   <owl:Class rdf:about=\"premises004#A-and-B\">\n"
				+ "     <owl:oneOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Thing rdf:about=\"premises004#a\"/>\n"
				+ "       <owl:Thing rdf:about=\"premises004#b\"/>\n"
				+ "     </owl:oneOf>\n" + "   </owl:Class>\n" + "\n" + "</rdf:RDF>";
		String id = "WebOnt_unionOf_004";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "An inverse to test <a xmlns=\"http://www.w3.org/1999/xhtml\" href=\"#unionOf-003\">003</a>.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
