package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_I5_5_005 {
    @Test
    public void testWebOnt_I5_5_005() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/I5.5/premises005\" >\n"
                + "    <owl:Class rdf:ID=\"a\" />\n" + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/I5.5/conclusions005\" >\n"
                + "   \n"
                + "   <owl:Class>\n"
                + "     <owl:unionOf>\n"
                + "       <rdf:List>\n"
                + "         <rdf:first>\n"
                + "           <owl:Class rdf:about=\"premises005#a\"/>\n"
                + "         </rdf:first>\n"
                + "         <rdf:rest rdf:resource = \"http://www.w3.org/1999/02/22-rdf-syntax-ns#nil\"/>\n"
                + "       </rdf:List>\n" + "     </owl:unionOf>\n" + "   </owl:Class>\n"
                + "\n" + "</rdf:RDF>";
        String id = "WebOnt_I5_5_005";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "This test exhibits the effect of the comprehension principles in OWL Full.  The conclusion ontology only contains a class declaration, ObjectUnionOf class expression does not appear in an axiom.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
