package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_equivalentProperty_002 {
	@Test
	public void testWebOnt_equivalentProperty_002() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/equivalentProperty/premises002#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/equivalentProperty/premises002\" >\n"
				+ "   <owl:Ontology/>\n" + "   <owl:ObjectProperty rdf:ID=\"hasHead\">\n"
				+ "      <owl:equivalentProperty>\n"
				+ "         <owl:ObjectProperty rdf:ID=\"hasLeader\"/>\n"
				+ "      </owl:equivalentProperty>\n" + "   </owl:ObjectProperty>\n"
				+ "</rdf:RDF>";
		String conclusion = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/equivalentProperty/premises002#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/equivalentProperty/conclusions002\" >\n"
				+ "   <owl:Ontology/>\n"
				+ "   <owl:ObjectProperty rdf:about=\"premises002#hasHead\">\n"
				+ "      <rdfs:subPropertyOf rdf:resource=\"premises002#hasLeader\"/>\n"
				+ "   </owl:ObjectProperty>\n"
				+ "   <owl:ObjectProperty rdf:about=\"premises002#hasLeader\">\n"
				+ "      <rdfs:subPropertyOf rdf:resource=\"premises002#hasHead\"/>\n"
				+ "   </owl:ObjectProperty>\n" + "</rdf:RDF>";
		String id = "WebOnt_equivalentProperty_002";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "A reasoner can also deduce that <code>hasLeader</code> is a <code>subProperty</code> of <code>hasHead</code> and <code>hasHead</code> is a <code>subProperty</code> of <code>hasLeader</code>.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
