package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_miscellaneous_302_Direct {
	@Test
	public void testWebOnt_miscellaneous_302_Direct() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/miscellaneous/premises302#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/miscellaneous/premises302\" >\n"
				+ "\n" + "<owl:Ontology/>\n"
				+ "<owl:AnnotationProperty rdf:ID=\"prop\" />\n"
				+ "<owl:Thing rdf:about=\"#a\">\n" + "   <first:prop>foo</first:prop>\n"
				+ "</owl:Thing>\n" + "\n" + "</rdf:RDF>";
		String conclusion = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/miscellaneous/premises302#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/miscellaneous/nonconclusions302\" >\n"
				+ "\n" + "<owl:Ontology/>\n" + "\n"
				+ "<owl:AnnotationProperty rdf:about=\"premises302#prop\" />\n" + "\n"
				+ "<owl:Thing rdf:about=\"premises302#a\">\n"
				+ "   <first:prop>bar</first:prop>\n" + "</owl:Thing>\n" + "\n"
				+ "</rdf:RDF>";
		String id = "WebOnt_miscellaneous_302_Direct";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "A version of WebOnt-miscellaneous-302 applicable under the Direct Semantics, in which the annotation in the entailed ontology is not considered.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
