package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_oneOf_001 {
    @Test
    public void testWebOnt_oneOf_001() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:first=\"http://www.w3.org/2002/03owlt/oneOf/consistent001#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/oneOf/consistent001\" >\n"
                + "   <owl:Ontology/>\n" + "   <owl:Class>\n"
                + "      <owl:oneOf rdf:parseType=\"Collection\">\n"
                + "         <rdf:Description rdf:ID=\"amy\"/>\n"
                + "         <rdf:Description rdf:ID=\"bob\"/>\n"
                + "         <rdf:Description rdf:ID=\"caroline\"/>\n"
                + "      </owl:oneOf>\n" + "      <owl:equivalentClass>\n"
                + "           <owl:Class>\n"
                + "             <owl:oneOf rdf:parseType=\"Collection\">\n"
                + "               <rdf:Description rdf:ID=\"yolanda\"/>\n"
                + "               <rdf:Description rdf:ID=\"zebedee\"/>\n"
                + "             </owl:oneOf>\n" + "           </owl:Class>\n"
                + "      </owl:equivalentClass>\n" + "   </owl:Class>\n" + "\n"
                + "</rdf:RDF>";
        String conclusion = "";
        String id = "WebOnt_oneOf_001";
        TestClasses tc = TestClasses.valueOf("CONSISTENCY");
        String d = "<code>oneOf</code> <em>does not</em> indicate that the named\n"
                + "individuals are distinct. Thus a consistent interpretation\n"
                + "of this file is when all the individual names denote the\n"
                + "same individual.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
