package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_Restriction_004 {
    @Test
    public void testWebOnt_Restriction_004() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/Restriction/consistent004\" >\n"
                + "   <owl:Ontology/>\n" + "   <owl:DatatypeProperty rdf:ID=\"dp\"/>\n"
                + "   <owl:Class rdf:ID=\"C\">\n"
                + "     <owl:intersectionOf rdf:parseType=\"Collection\">\n"
                + "        <owl:Class rdf:ID=\"superC\"/>\n"
                + "        <owl:Restriction>\n"
                + "           <owl:onProperty rdf:resource=\"#dp\"/>\n"
                + "           <owl:someValuesFrom rdf:resource=\n"
                + "     \"http://www.w3.org/2001/XMLSchema#byte\" />\n"
                + "        </owl:Restriction>\n" + "     </owl:intersectionOf>\n"
                + "   </owl:Class>\n" + "   <owl:Class rdf:ID=\"D\">\n"
                + "     <owl:intersectionOf rdf:parseType=\"Collection\">\n"
                + "        <owl:Class rdf:ID=\"superD\"/>\n"
                + "        <owl:Restriction>\n"
                + "           <owl:onProperty rdf:resource=\"#dp\"/>\n"
                + "           <owl:someValuesFrom rdf:resource=\n"
                + "     \"http://www.w3.org/2001/XMLSchema#byte\" />\n"
                + "        </owl:Restriction>\n" + "     </owl:intersectionOf>\n"
                + "   </owl:Class>\n" + "\n" + "</rdf:RDF>";
        String conclusion = "";
        String id = "WebOnt_Restriction_004";
        TestClasses tc = TestClasses.valueOf("CONSISTENCY");
        String d = "This test shows OWL Lite syntax for using two equivalent restrictions.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
