package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_AnnotationProperty_004 {
    @Test
    public void testWebOnt_AnnotationProperty_004() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\n"
                + "\"http://www.w3.org/2002/03owlt/AnnotationProperty/consistent004\" >\n"
                + "\n" + "   <owl:Ontology />\n" + "\n"
                + "   <owl:AnnotationProperty rdf:ID=\"ap\">\n"
                + "     <rdfs:range rdf:resource=\n"
                + "  \"http://www.w3.org/2001/XMLSchema#string\"/>\n"
                + "   </owl:AnnotationProperty>\n" + "</rdf:RDF>";
        String conclusion = "";
        String id = "WebOnt_AnnotationProperty_004";
        TestClasses tc = TestClasses.valueOf("CONSISTENCY");
        String d = "AnnotationProperty's in OWL Lite and OWL DL, may not have range constraints.  They are permitted in OWL 2 DL.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
