package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_cardinality_004 {
    @Test
    public void testWebOnt_cardinality_004() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/cardinality/premises004\" >    \n"
                + "    <owl:Ontology/>\n"
                + "    <owl:Class rdf:about=\"conclusions004#c\">\n"
                + "      <rdfs:subClassOf>\n"
                + "          <owl:Class>\n"
                + "             <owl:intersectionOf rdf:parseType=\"Collection\">\n"
                + "                <owl:Restriction>\n"
                + "                   <owl:onProperty rdf:resource=\"conclusions004#p\"/>\n"
                + "                   <owl:maxCardinality\n"
                + " rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
                + "                   >2</owl:maxCardinality>\n"
                + "                </owl:Restriction>\n"
                + "                <owl:Restriction>\n"
                + "                   <owl:onProperty rdf:resource=\"conclusions004#p\"/>\n"
                + "                   <owl:minCardinality\n"
                + " rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
                + "                   >2</owl:minCardinality>\n"
                + "                </owl:Restriction>\n"
                + "              </owl:intersectionOf>\n" + "           </owl:Class>\n"
                + "       </rdfs:subClassOf>\n" + "     </owl:Class>\n"
                + "     <owl:ObjectProperty rdf:about=\"conclusions004#p\"/>\n"
                + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/cardinality/conclusions004\" >\n"
                + "    <owl:Ontology/>\n"
                + "    <owl:Class rdf:ID=\"c\">\n"
                + "      <rdfs:subClassOf>\n"
                + "                <owl:Restriction>\n"
                + "                   <owl:onProperty rdf:resource=\"#p\"/>\n"
                + "                   <owl:cardinality\n"
                + " rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\"\n"
                + "                   >2</owl:cardinality>\n"
                + "                </owl:Restriction>\n" + "       </rdfs:subClassOf>\n"
                + "     </owl:Class>\n" + "     <owl:ObjectProperty rdf:ID=\"p\"/>\n"
                + "</rdf:RDF>";
        String id = "WebOnt_cardinality_004";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "An <code>owl:cardinality</code> constraint is simply shorthand for a pair of <code>owl:minCardinality</code> and <code>owl:maxCardinality</code> constraints.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
