package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_Nothing_001 {
	@Test
	public void testWebOnt_Nothing_001() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/Nothing/inconsistent001\" >\n"
				+ "\n" + "  <owl:Ontology/>\n" + "  <owl:Nothing/>\n" + "\n"
				+ "</rdf:RDF>";
		String conclusion = "";
		String id = "WebOnt_Nothing_001";
		TestClasses tc = TestClasses.valueOf("INCONSISTENCY");
		String d = "The triple asserts something of type <code>owl:Nothing</code>, however\n"
				+ "that is the empty class.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
