package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_unionOf_003 {
	@Test
	public void testWebOnt_unionOf_003() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/unionOf/premises003\" >\n"
				+ "   <owl:Ontology/>\n" + "   <owl:Class rdf:ID=\"A\">\n"
				+ "     <owl:oneOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Thing rdf:ID=\"a\"/>\n" + "     </owl:oneOf>\n"
				+ "   </owl:Class>\n" + "   <owl:Class rdf:ID=\"B\">\n"
				+ "     <owl:oneOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Thing rdf:ID=\"b\"/>\n" + "     </owl:oneOf>\n"
				+ "   </owl:Class>\n" + "   <owl:Class rdf:ID=\"A-and-B\">\n"
				+ "     <owl:oneOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Thing rdf:about=\"#a\"/>\n"
				+ "       <owl:Thing rdf:about=\"#b\"/>\n" + "     </owl:oneOf>\n"
				+ "   </owl:Class>\n" + "\n" + "</rdf:RDF>";
		String conclusion = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/unionOf/conclusions003\" >\n"
				+ "   \n" + "\n" + "   <owl:Ontology/>\n"
				+ "   <owl:Class rdf:about=\"premises003#A-and-B\">\n"
				+ "     <owl:unionOf rdf:parseType=\"Collection\">\n"
				+ "       <owl:Class rdf:about=\"premises003#A\"/>\n"
				+ "       <owl:Class rdf:about=\"premises003#B\"/>\n"
				+ "     </owl:unionOf>\n" + "   </owl:Class>\n" + "\n" + "\n"
				+ "</rdf:RDF>";
		String id = "WebOnt_unionOf_003";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "Sets with appropriate extensions are related by unionOf.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
