package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_SymmetricProperty_003 {
    @Test
    public void testWebOnt_SymmetricProperty_003() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:first=\"http://www.w3.org/2002/03owlt/SymmetricProperty/premises003#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/SymmetricProperty/premises003\" >\n"
                + "\n" + "    <owl:Ontology/>\n" + "\n"
                + "    <owl:Thing rdf:about=\"premises003#Ghent\">\n"
                + "        <first:path>\n"
                + "           <owl:Thing rdf:about=\"premises003#Antwerp\"/>\n"
                + "        </first:path>\n" + "    </owl:Thing>\n" + "\n"
                + "    <owl:SymmetricProperty rdf:about=\"premises003#path\"/>\n" + "\n"
                + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:first=\"http://www.w3.org/2002/03owlt/SymmetricProperty/premises003#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/SymmetricProperty/conclusions003\" >\n"
                + "\n" + "    <owl:Ontology/>\n" + "\n"
                + "    <owl:Thing rdf:about=\"premises003#Antwerp\">\n"
                + "        <first:path>\n"
                + "          <owl:Thing rdf:about=\"premises003#Ghent\"/>\n"
                + "        </first:path>\n" + "    </owl:Thing>\n" + "\n"
                + "    <owl:ObjectProperty rdf:about=\"premises003#path\"/>\n" + "\n"
                + "</rdf:RDF>";
        String id = "WebOnt_SymmetricProperty_003";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "A Lite version of test <a xmlns=\"http://www.w3.org/1999/xhtml\" href=\"#SymmetricProperty-001\">001</a>.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
