package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_disjointWith_001 {
	@Test
	public void testWebOnt_disjointWith_001() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/disjointWith/premises001#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/disjointWith/premises001\" >\n"
				+ "   <owl:Ontology/>\n" + "   <owl:Class rdf:ID=\"A\">\n"
				+ "      <owl:disjointWith>\n" + "           <owl:Class rdf:ID=\"B\"/>\n"
				+ "      </owl:disjointWith>\n" + "   </owl:Class>\n"
				+ "   <first:A rdf:ID=\"a\"/>\n" + "   <owl:Thing rdf:about=\"#a\"/>\n"
				+ "   <first:B rdf:ID=\"b\"/>\n" + "   <owl:Thing rdf:about=\"#b\"/>\n"
				+ "</rdf:RDF>";
		String conclusion = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xmlns:first=\"http://www.w3.org/2002/03owlt/disjointWith/premises001#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/disjointWith/conclusions001\" >\n"
				+ "   <owl:Ontology/>\n"
				+ "    <owl:Thing rdf:about=\"premises001#a\">\n"
				+ "       <owl:differentFrom>\n"
				+ "          <owl:Thing rdf:about=\"premises001#b\"/>\n"
				+ "       </owl:differentFrom>\n" + "    </owl:Thing>\n" + "</rdf:RDF>";
		String id = "WebOnt_disjointWith_001";
		TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
		String d = "Disjoint classes have different members.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
