package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_miscellaneous_303 {
	@Test
	public void testWebOnt_miscellaneous_303() {
		String premise = "<rdf:RDF\n"
				+ "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
				+ "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
				+ "    xml:base=\"http://www.w3.org/2002/03owlt/miscellaneous/consistent303\" >\n"
				+ "\n"
				+ "  <owl:Ontology/>\n"
				+ "  <owl:AnnotationProperty rdf:about='http://purl.org/dc/elements/1.0/creator'/>\n"
				+ "\n" + "</rdf:RDF>";
		String conclusion = "";
		String id = "WebOnt_miscellaneous_303";
		TestClasses tc = TestClasses.valueOf("CONSISTENCY");
		String d = "<code>dc:creator</code> may be declared as an annotation property.";
		JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
		r.setReasonerFactory(Factory.factory());
		r.run();
	}
}
