package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_equivalentClass_002 {
    @Test
    public void testWebOnt_equivalentClass_002() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/equivalentClass/premises002\" >\n"
                + "   <owl:Ontology/>\n" + "   <owl:Class rdf:ID=\"Car\">\n"
                + "     <owl:equivalentClass>\n"
                + "       <owl:Class rdf:ID=\"Automobile\"/>\n"
                + "     </owl:equivalentClass>\n" + "  </owl:Class>\n" + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/equivalentClass/conclusions002\" >\n"
                + "   <owl:Ontology/>\n"
                + "   <owl:Class rdf:about=\"premises002#Car\">\n"
                + "     <rdfs:subClassOf>\n"
                + "       <owl:Class rdf:about=\"premises002#Automobile\">\n"
                + "          <rdfs:subClassOf rdf:resource=\"premises002#Car\" />\n"
                + "       </owl:Class>\n" + "     </rdfs:subClassOf>\n"
                + "  </owl:Class>\n" + "</rdf:RDF>";
        String id = "WebOnt_equivalentClass_002";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "Two classes may be different names for the same set of individuals";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
