package conformance.autogenerated;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_I4_6_005_Direct {
    @Test
    public void testWebOnt_I4_6_005_Direct() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/I4.6/premises005\" >\n"
                + "    <owl:Ontology/>\n"
                + "    <owl:Class rdf:about=\"nonconclusions005#C1\">\n"
                + "       <rdfs:comment>An example class.</rdfs:comment>\n"
                + "       <owl:equivalentClass>\n"
                + "           <owl:Class rdf:about=\"nonconclusions005#C2\"/>\n"
                + "       </owl:equivalentClass>\n" + "    </owl:Class>\n" + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/I4.6/nonconclusions005\" >\n"
                + "    <owl:Ontology/>\n" + "    <owl:Class rdf:ID=\"C2\">\n"
                + "       <rdfs:comment>An example class.</rdfs:comment>\n"
                + "    </owl:Class>\n" + "</rdf:RDF>";
        String id = "WebOnt_I4_6_005_Direct";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "Under the direct semantics, test WebOnt-I4.6-005 must be treated as a positive entailment test because the direct semantics ignore annotations in the conclusion ontology.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
