package conformance.fixed;

import org.junit.Test;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.reasoner.OWLReasoner;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_miscellaneous_002 {
    @Test
    public void testWebOnt_miscellaneous_002() {
        String conclusion = "";
        String id = "WebOnt_miscellaneous_002";
        TestClasses tc = TestClasses.valueOf("CONSISTENCY");
        String d = "Food example taken from the guide. Note that this is the same as the ontology http://www.w3.org/2002/03owlt/miscellaneous/consistent002 imported in other tests.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }

    public void _testWebOnt_miscellaneous_002(String s1, String s2)
            throws OWLOntologyCreationException {
        String conclusion = "";
        String id = "WebOnt_miscellaneous_002";
        TestClasses tc = TestClasses.valueOf("CONSISTENCY");
        String d = "Food example taken from the guide. Note that this is the same as the ontology http://www.w3.org/2002/03owlt/miscellaneous/consistent002 imported in other tests.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.getConfiguration().setorSortSat(s1);
        r.getConfiguration().setorSortSub(s2);
        // r.getConfiguration().setLoggingActive(true);
        // r.setReasonerFactory(Factory.factory());
        try {
            long start = System.currentTimeMillis();
            OWLReasoner reasoner = Factory.factory().createReasoner(r.getPremise(),
                    r.getConfiguration());
            System.out.println("WebOnt_miscellaneous_002.testWebOnt_miscellaneous_002() "
                    + reasoner.isConsistent());
            // r.run();
            System.out
                    .println("WebOnt_miscellaneous_002.testWebOnt_miscellaneous_002() done in "
                            + (System.currentTimeMillis() - start));
        } catch (RuntimeException e) {
            System.out.println("WebOnt_miscellaneous_002.testWebOnt_miscellaneous_002() "
                    + e.getMessage());
        }
    }

    private static String[] options = new String[] { "Sap", "Sdp", "San", "Sdn", "Dap",
            "Ddp", "Dan", "Ddn", "Fap", "Fdp", "Fan", "Fdn", "Bap", "Bdp", "Ban", "Bdn",
            "Gap", "Gdp", "Gan", "Gdn" };

    public static void main(String[] args) throws OWLOntologyCreationException {
        WebOnt_miscellaneous_002 t = new WebOnt_miscellaneous_002();
        for (String s1 : options) {
            for (String s2 : options) {
                t._testWebOnt_miscellaneous_002(s1, s2);
            }
        }
    }

    private static String premise = "<!DOCTYPE owl [\n"
            + "     <!ENTITY vin  \"http://www.w3.org/2002/03owlt/miscellaneous/consistent001#\" >\n"
            + "     <!ENTITY food \"http://www.w3.org/2002/03owlt/miscellaneous/consistent002#\" >\n"
            + "     <!ENTITY xsd  \"http://www.w3.org/2001/XMLSchema#\" >\n"
            + "   ]>\n"
            + "\n"
            + "<rdf:RDF\n"
            + "  xmlns     = \"&food;\"\n"
            + "  xmlns:food= \"&food;\"\n"
            + "  xml:base  = \"&food;\"\n"
            + "  xmlns:vin = \"&vin;\"\n"
            + "  xmlns:owl = \"http://www.w3.org/2002/07/owl#\"\n"
            + "  xmlns:rdf = \"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
            + "  xmlns:rdfs= \"http://www.w3.org/2000/01/rdf-schema#\">\n"
            + "\n"
            + "  <owl:Ontology rdf:about=\"\">\n"
            + "    <rdfs:comment>\n"
            + "      Derived from the DAML Wine ontology at \n"
            + "      http://ontolingua.stanford.edu/doc/chimaera/ontologies/wines.daml\n"
            + "      Substantially modified.\n"
            + "    </rdfs:comment> \n"
            + "    <owl:imports rdf:resource=\"http://www.w3.org/2002/03owlt/miscellaneous/consistent001\"/>\n"
            + "  </owl:Ontology>\n"
            + "\n"
            + "  <owl:Class rdf:ID=\"ConsumableThing\" />\n"
            + "\n"
            + "  <owl:Class rdf:ID=\"NonConsumableThing\">\n"
            + "    <owl:complementOf rdf:resource=\"#ConsumableThing\" />\n"
            + "  </owl:Class>\n"
            + "\n"
            + "  <owl:Class rdf:ID=\"EdibleThing\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#ConsumableThing\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PotableLiquid\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#ConsumableThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#EdibleThing\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"Wine\">\n"
            + "    <owl:equivalentClass rdf:resource=\"&vin;Wine\"/>\n"
            + "  </owl:Class>\n"
            + "\n"
            + "  <owl:ObjectProperty rdf:ID=\"madeFromFruit\">\n"
            + "    <rdfs:domain rdf:resource=\"#ConsumableThing\" />\n"
            + "    <rdfs:range rdf:resource=\"#Fruit\" />\n"
            + "  </owl:ObjectProperty>\n"
            + "\n"
            + "  <owl:Class rdf:ID=\"Juice\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#PotableLiquid\" />\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#madeFromFruit\" />\n"
            + "  <owl:minCardinality rdf:datatype=\"&xsd;nonNegativeInteger\">1</owl:minCardinality>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "\n"
            + "  <owl:ObjectProperty rdf:ID=\"hasDrink\">\n"
            + "    <rdfs:domain rdf:resource=\"#MealCourse\" />\n"
            + "    <rdfs:range rdf:resource=\"#PotableLiquid\" />\n"
            + "  </owl:ObjectProperty>\n"
            + "  \n"
            + "  <owl:Thing rdf:ID=\"White\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;White\"/>\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Rose\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Rose\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Red\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Red\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Sweet\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Sweet\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"OffDry\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;OffDry\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Dry\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Dry\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Delicate\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Delicate\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Moderate\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Moderate\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Strong\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Strong\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Light\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Light\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Medium\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Medium\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:Thing rdf:ID=\"Full\">\n"
            + "    <owl:sameAs rdf:resource=\"&vin;Full\" />\n"
            + "  </owl:Thing>\n"
            + "\n"
            + "  <owl:ObjectProperty rdf:ID=\"course\">\n"
            + "    <rdfs:domain rdf:resource=\"#Meal\" />\n"
            + "    <rdfs:range rdf:resource=\"#MealCourse\" />\n"
            + "  </owl:ObjectProperty>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"Grape\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#SweetFruit\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"Pasta\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Meat\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fowl\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Seafood\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Dessert\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fruit\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithWhiteSauce\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Pasta\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#PastaWithRedSauce\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithSpicyRedSauceCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#PastaWithSpicyRedSauce\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Full\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Strong\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithSpicyRedSauce\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#PastaWithRedSauce\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithRedSauce\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Pasta\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithNonSpicyRedSauceCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#PastaWithNonSpicyRedSauce\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithNonSpicyRedSauce\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#PastaWithRedSauce\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#PastaWithSpicyRedSauce\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithLightCreamSauce\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#PastaWithWhiteSauce\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#PastaWithHeavyCreamSauce\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithLightCreamCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#PastaWithLightCreamSauce\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Light\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Delicate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithHeavyCreamSauce\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#PastaWithWhiteSauce\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"PastaWithHeavyCreamCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#PastaWithHeavyCreamSauce\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"OysterShellfishCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#OysterShellfish\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Sweet\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"OysterShellfish\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Shellfish\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"OtherTomatoBasedFoodCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#OtherTomatoBasedFood\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"OtherTomatoBasedFood\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Pasta\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Meat\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fowl\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Seafood\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Dessert\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fruit\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonSweetFruitCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#NonSweetFruit\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Delicate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#OffDry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"SweetFruitCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#SweetFruit\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Sweet\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "   \n"
            + "  <owl:Class rdf:ID=\"NonSweetFruit\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#SweetFruit\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonSpicyRedMeatCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#NonSpicyRedMeat\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:allValuesFrom>\n"
            + "              <owl:Class>\n"
            + "                <owl:oneOf rdf:parseType=\"Collection\">\n"
            + "                  <owl:Thing rdf:about=\"#Strong\" />\n"
            + "                  <owl:Thing rdf:about=\"#Moderate\" />\n"
            + "                </owl:oneOf>\n"
            + "              </owl:Class>\n"
            + "            </owl:allValuesFrom>\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonSpicyRedMeat\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#RedMeat\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#SpicyRedMeat\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonRedMeatCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#NonRedMeat\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Strong\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonRedMeat\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Meat\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#RedMeat\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonOysterShellfishCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#NonOysterShellfish\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonOysterShellfish\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Shellfish\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#OysterShellfish\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonBlandFishCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#NonBlandFish\" />\n"
            + "      </owl:Restriction>\n"
            + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n"
            + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"NonBlandFish\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Fish\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"Meat\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fowl\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Seafood\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Dessert\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fruit\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"MealCourse\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#ConsumableThing\" />\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:minCardinality rdf:datatype=\"&xsd;nonNegativeInteger\">1</owl:minCardinality>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:minCardinality rdf:datatype=\"&xsd;nonNegativeInteger\">1</owl:minCardinality>\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#Wine\" />\n"
            + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n"
            + "    <owl:disjointWith rdf:resource=\"#PotableLiquid\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#EdibleThing\" />\n"
            + "  </owl:Class>\n"
            + "  \n"
            + "  <owl:Class rdf:ID=\"Meal\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#ConsumableThing\" />\n"
            + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#course\" />\n"
            + "        <owl:minCardinality rdf:datatype=\"&xsd;nonNegativeInteger\">1</owl:minCardinality>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#course\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#MealCourse\" />\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <owl:disjointWith rdf:resource=\"#MealCourse\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#PotableLiquid\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#EdibleThing\" />\n"
            + "  </owl:Class>\n" + "  \n"
            + "  <owl:Class rdf:ID=\"LightMeatFowlCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#LightMeatFowl\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"LightMeatFowl\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Fowl\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <owl:Class rdf:ID=\"FruitCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#Fruit\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + " \n" + "  \n"
            + "  <owl:Class rdf:ID=\"Fruit\">\n"
            + "    <owl:unionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#SweetFruit\" />\n"
            + "      <owl:Class rdf:about=\"#NonSweetFruit\" />\n"
            + "    </owl:unionOf>\n" + "  </owl:Class>\n" + "  \n"
            + "  <owl:Class rdf:ID=\"Fowl\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Seafood\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Dessert\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fruit\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <owl:Class rdf:ID=\"FishCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#Fish\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Medium\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"DessertCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#Dessert\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Full\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Strong\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Sweet\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"Dessert\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fruit\" />\n" + "  </owl:Class>\n"
            + "  \n" + "   <owl:Class rdf:ID=\"SweetFruit\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "  </owl:Class>\n" + "  \n"
            + "  <owl:Class rdf:ID=\"SweetDessertCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#SweetDessert\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"SweetDessert\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Dessert\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <owl:Class rdf:ID=\"DarkMeatFowlCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#DarkMeatFowl\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Light\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Delicate\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"DarkMeatFowl\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Fowl\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#LightMeatFowl\" />\n"
            + "  </owl:Class>\n" + "  \n"
            + "  <owl:Class rdf:ID=\"CheeseNutsDessertCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#CheeseNutsDessert\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n"
            + "  <owl:Class rdf:ID=\"CheeseNutsDessert\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Dessert\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#SweetDessert\" />\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"BlandFishCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#BlandFish\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Delicate\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"BlandFish\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Fish\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#NonBlandFish\" />\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:ObjectProperty rdf:ID=\"hasFood\">\n"
            + "    <rdfs:domain rdf:resource=\"#MealCourse\" />\n"
            + "    <rdfs:range rdf:resource=\"#EdibleThing\" />\n"
            + "  </owl:ObjectProperty>\n" + "  \n" + "  <owl:Class rdf:ID=\"Fish\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Seafood\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Shellfish\" />\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"SpicyRedMeat\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#RedMeat\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <owl:Class rdf:ID=\"ShellfishCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#Shellfish\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:allValuesFrom>\n" + "              <owl:Class>\n"
            + "                <owl:oneOf rdf:parseType=\"Collection\">\n"
            + "                  <owl:Thing rdf:about=\"#Moderate\" />\n"
            + "                  <owl:Thing rdf:about=\"#Strong\" />\n"
            + "                </owl:oneOf>\n" + "              </owl:Class>\n"
            + "            </owl:allValuesFrom>\n" + "          </owl:Restriction>\n"
            + "        </owl:allValuesFrom>\n" + "      </owl:Restriction>\n"
            + "    </rdfs:subClassOf>\n" + "    <rdfs:subClassOf>\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Full\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"Shellfish\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Seafood\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <owl:Class rdf:ID=\"SeafoodCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#Seafood\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#White\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"Seafood\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#EdibleThing\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Dessert\" />\n"
            + "    <owl:disjointWith rdf:resource=\"#Fruit\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <owl:Class rdf:ID=\"RedMeatCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#RedMeat\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <owl:Class rdf:ID=\"RedMeat\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Meat\" />\n" + "  </owl:Class>\n"
            + "  \n" + "  <SweetDessert rdf:ID=\"Cake\" />\n" + "  \n"
            + "  <SweetFruit rdf:ID=\"Bananas\" />\n" + "  \n"
            + "  <SweetFruit rdf:ID=\"MixedFruit\" />\n" + "  \n"
            + "  <NonOysterShellfish rdf:ID=\"Mussels\" />\n" + "  \n"
            + "  <CheeseNutsDessert rdf:ID=\"Nuts\" />\n" + "  \n"
            + "  <OysterShellfish rdf:ID=\"Oysters\" />\n" + "  \n"
            + "  <PastaWithLightCreamSauce rdf:ID=\"PastaWithWhiteClamSauce\" />\n"
            + "  \n" + "  <SweetFruit rdf:ID=\"Peaches\" />\n" + "  \n"
            + "  <SweetDessert rdf:ID=\"Pie\" />\n" + "  \n"
            + "  <OtherTomatoBasedFood rdf:ID=\"Pizza\" />\n" + "  \n"
            + "  <NonRedMeat rdf:ID=\"Pork\" />\n" + "  \n"
            + "  <NonSpicyRedMeat rdf:ID=\"RoastBeef\" />\n" + "  \n"
            + "  <BlandFish rdf:ID=\"Scrod\" />\n" + "  \n"
            + "  <PastaWithNonSpicyRedSauce rdf:ID=\"SpaghettiWithTomatoSauce\" />\n"
            + "  \n" + "  <NonSpicyRedMeat rdf:ID=\"Steak\" />\n" + "  \n"
            + "  <NonBlandFish rdf:ID=\"Swordfish\" />\n" + "  \n"
            + "  <EatingGrape rdf:ID=\"ThompsonSeedless\" />\n" + "  \n"
            + "  <owl:Class rdf:ID=\"EatingGrape\">\n"
            + "    <rdfs:subClassOf rdf:resource=\"#Grape\" />\n" + "  </owl:Class>\n"
            + "\n" + "  <NonBlandFish rdf:ID=\"Tuna\" />\n" + "  \n"
            + "  <LightMeatFowl rdf:ID=\"Turkey\" />\n" + "  \n"
            + "  <NonSpicyRedMeat rdf:ID=\"Veal\" />\n" + "  \n"
            + "  <owl:Class rdf:ID=\"SpicyRedMeatCourse\">\n"
            + "    <owl:intersectionOf rdf:parseType=\"Collection\">\n"
            + "      <owl:Class rdf:about=\"#MealCourse\" />\n"
            + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasFood\" />\n"
            + "        <owl:allValuesFrom rdf:resource=\"#SpicyRedMeat\" />\n"
            + "      </owl:Restriction>\n" + "    </owl:intersectionOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasColor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Red\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasBody\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Full\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasFlavor\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Moderate\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "    <rdfs:subClassOf>\n" + "      <owl:Restriction>\n"
            + "        <owl:onProperty rdf:resource=\"#hasDrink\" />\n"
            + "        <owl:allValuesFrom>\n" + "          <owl:Restriction>\n"
            + "            <owl:onProperty rdf:resource=\"&vin;hasSugar\" />\n"
            + "            <owl:hasValue rdf:resource=\"#Dry\" />\n"
            + "          </owl:Restriction>\n" + "        </owl:allValuesFrom>\n"
            + "      </owl:Restriction>\n" + "    </rdfs:subClassOf>\n"
            + "  </owl:Class>\n" + "  \n" + "  <SpicyRedMeat rdf:ID=\"BeefCurry\" />\n"
            + "  \n" + "  <LightMeatFowl rdf:ID=\"Chicken\" />\n" + "  \n"
            + "  <NonOysterShellfish rdf:ID=\"Clams\" />\n" + "  \n"
            + "  <DarkMeatFowl rdf:ID=\"Duck\" />\n" + "  \n"
            + "  <SpicyRedMeat rdf:ID=\"GarlickyRoast\" />\n" + "  \n"
            + "  <DarkMeatFowl rdf:ID=\"Goose\" />\n" + "  \n"
            + "  <BlandFish rdf:ID=\"Halibut\" />\n" + "  \n"
            + "  <NonOysterShellfish rdf:ID=\"Crab\" />\n" + "  \n"
            + "  <BlandFish rdf:ID=\"Flounder\" />\n" + "  \n"
            + "  <NonOysterShellfish rdf:ID=\"Lobster\" />\n" + "  \n"
            + "  <PastaWithHeavyCreamSauce rdf:ID=\"FettucineAlfRedo\" />\n" + "  \n"
            + "  <PastaWithSpicyRedSauce rdf:ID=\"FraDiavolo\" />\n" + "  \n"
            + "  <CheeseNutsDessert rdf:ID=\"Cheese\" />\n" + "  \n" + "</rdf:RDF>";
}
