package conformance.fixed;

import org.junit.Test;

import conformance.Factory;
import conformance.JUnitRunner;
import conformance.TestClasses;

public class WebOnt_I5_21_002 {
    @Test
    public void testWebOnt_I5_21_002() {
        String premise = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xmlns:first=\"http://www.w3.org/2002/03owlt/I5.21/premises002#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/I5.21/premises002\" >\n"
                + "\n" + "   <owl:Ontology/>\n" + "   <owl:Class rdf:ID=\"Reptile\">\n"
                + "     <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "           <owl:onProperty>\n"
                + "              <owl:DatatypeProperty rdf:ID=\"family-name\"/>\n"
                + "           </owl:onProperty>\n"
                + "           <owl:cardinality rdf:datatype=\n"
                + " \"http://www.w3.org/2001/XMLSchema#int\">1</owl:cardinality>\n"
                + "        </owl:Restriction>\n" + "     </rdfs:subClassOf>\n"
                + "   </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Amphisbaenidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Amphisbaenidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Agamidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Agamidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Anomalepidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Anomalepidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "          \n"
                + "    <owl:Class rdf:about=\"#Emydidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Emydidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Crocodylidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Crocodylidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Gekkonidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Gekkonidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Sphenodontidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Sphenodontidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Cordylidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Cordylidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Bipedidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Bipedidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Leptotyphlopidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Leptotyphlopidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Xantusiidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Xantusiidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"#Loxocemidae\">\n"
                + "      <rdfs:subClassOf rdf:resource=\"#Reptile\" />\n"
                + "      <rdfs:subClassOf>\n" + "        <owl:Restriction>\n"
                + "          <owl:onProperty rdf:resource=\"#family-name\"/>\n"
                + "          <owl:hasValue>Loxocemidae</owl:hasValue>\n"
                + "        </owl:Restriction>\n" + "      </rdfs:subClassOf>\n"
                + "    </owl:Class>\n" + "\n" + "\n" + "</rdf:RDF>";
        String conclusion = "<rdf:RDF\n"
                + "    xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "    xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "    xml:base=\"http://www.w3.org/2002/03owlt/I5.21/conclusions002\" >\n"
                + "\n"
                + "    <owl:Ontology/>\n"
                + "    <owl:Class rdf:about=\"premises002#Amphisbaenidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Agamidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Anomalepidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Emydidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Crocodylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Gekkonidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Sphenodontidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Agamidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Anomalepidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Emydidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Crocodylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Gekkonidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Sphenodontidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Anomalepidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Emydidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Crocodylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Gekkonidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Sphenodontidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Emydidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Crocodylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Gekkonidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Sphenodontidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Crocodylidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Gekkonidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Sphenodontidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Gekkonidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Sphenodontidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Sphenodontidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Cordylidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Cordylidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Bipedidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n"
                + "\n"
                + "    <owl:Class rdf:about=\"premises002#Bipedidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Leptotyphlopidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"premises002#Leptotyphlopidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Xantusiidae\"/>\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"premises002#Xantusiidae\">\n"
                + "      <owl:disjointWith rdf:resource=\"premises002#Loxocemidae\"/>\n"
                + "    </owl:Class>\n" + "\n"
                + "    <owl:Class rdf:about=\"premises002#Loxocemidae\">\n"
                + "    </owl:Class>\n" + "\n" + "</rdf:RDF>";
        String id = "WebOnt_I5_21_002";
        TestClasses tc = TestClasses.valueOf("POSITIVE_IMPL");
        String d = "The construct used here shows how to express mutual disjointness between classes with  O(N) triples.";
        JUnitRunner r = new JUnitRunner(premise, conclusion, id, tc, d);
        r.setReasonerFactory(Factory.factory());
        r.run();
    }
}
